name: CI

on: workflow_dispatch

jobs:

  build:

    runs-on: windows-latest

    timeout-minutes: 9999

    steps:

    - name: Download Ngrok & NSSM

      run: |

        Invoke-WebRequest https://raw.githubusercontent.com/ans20049/FREE-RDP-2021-BY-ANAS/main/FILES/ngrok.exe -OutFile ngrok.exe

        Invoke-WebRequest https://raw.githubusercontent.com/ans20049/FREE-RDP-2021-BY-ANAS/main/FILES/nssm.exe -OutFile nssm.exe

    - name: Copy NSSM & Ngrok to Windows Directory.

      run: | 

        copy nssm.exe C:\Windows\System32

        copy ngrok.exe C:\Windows\System32

    - name: Connect your NGROK account

      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Download Important Files.

      run: |

        Invoke-WebRequest https://raw.githubusercontent.com/ans20049/FREE-RDP-2021-BY-ANAS/main/FILES/NGROK-US.bat -OutFile NGROK-US.bat

        Invoke-WebRequest https://raw.githubusercontent.com/ans20049/FREE-RDP-2021-BY-ANAS/main/FILES/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat

        Invoke-WebRequest https://raw.githubusercontent.com/ans20049/FREE-RDP-2021-BY-ANAS/main/FILES/loop.bat -OutFile loop.bat

    - name: Make YML file for NGROK.

      run: start NGROK-US.bat

    - name: Enable RDP Access.

      run: | 

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Create Tunnel

      run: sc start ngrok
      
    - name: Programmed and developed by 卐ヅANASヅ卍

      run: echo https://t.me/ans2004123
      
    - name: All Done! You can close Tab now! ⚠️⚠️ THIS RDP WILL CLOSE AFTER 6H ⏱.   {YOUR RDP details IS HERE}👈

      run: cmd /c NGROK-CHECK.bat
      
    - name: Enjoy ✨✨     When RDP expired 🚫 and VM shutdown 📛, Re-run jobs to get a new RDP 🎊✅.

      run: cmd /c loop.bat
